name: IcyTrolling
version: B-0.1
main: me.icynnac.icytrolling.Main
commands:
  icytroll:
    description: A command for stuff about the plugin.
    permission: icytroll.icytroll
  explode:
    description: Blows up someone on a 5 second timer.
    permission: icytroll.explode
  burn:
    description: buuuuuuuurn
    permission: icytroll.burn
  drop:
    description: Drop whatever your target's holding!
    permission: icytroll.drop
  pumpkin:
    description: Put a pumpkin on someone's head!
    permission: icytroll.pumpkin
  fling:
    description: Fling someone really high.
    permission: icytroll.fling
  levitate:
    description: Send someone to the sun.
    permission: icytroll.levitate
  lag:
    description: Have my internet.
    permission: icytroll.lag
  demo:
    description: You should pay for Minecraft.
    permission: icytroll.demo
  scam:
    description: Helo your computer have virus
    permission: icytroll.scam
  fakeexplode:
    description: Boom? Nope.
    permission: icytroll.fakeexplode
  rotate:
    description: Rotate someone to mess up their travel.
    permission: icytroll.rotate